name: Static Analysis

on:

    push:
        branches:
            - main

    pull_request:

jobs:

    phpstan:

        name: PHP Static Analysis
        runs-on: ubuntu-latest

        steps:

            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup tools
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  tools: cs2pr
                  coverage: none

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v3

            - name: Cache PHPStan
              uses: actions/cache@v4
              with:
                  path: var/phpstan/
                  key: phpstan-${{ github.sha }}
                  restore-keys: phpstan-

            - name: Run PHP Static Analysis
              run: vendor/bin/phpstan --no-progress --error-format=checkstyle | cs2pr
