name: Tests

on:

    push:
        branches:
            - main

    pull_request:

jobs:

    tests:

        name: PHPUnit (PHP ${{ matrix.php-version }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2']
                include:
                    - php-version: '8.0'
                      coverage: true

        steps:

            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  coverage: ${{ matrix.coverage && 'pcov' || 'none' }}

            - name: Install Pandoc
              run: sudo apt install pandoc

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v2

            - name: Run PHPUnit
              run: vendor/bin/phpunit --testdox ${{ matrix.coverage && '--coverage-clover ./coverage.xml' || '--no-coverage' }}

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              if: ${{ matrix.coverage }}
              with:
                  file: ./coverage.xml
